services:
  server:
    image: ${APP_NAME}:latest
    environment:
        PORT: 8080
        ORDERPACKER_CONFIG_PATH: ${ORDERPACKER_CONFIG_PATH:-}
    ports:
      - 8080:8080
    volumes:
        - ./configs:/configs

