services:
  server:
    image: ${APP_NAME}:latest
    environment:
        PORT: "8080"
        HOST: "0.0.0.0"
        PACK_BOXES: "1,2,4,8,16"
        LOG_LEVEL: "DEBUG"
        LOG_FORMAT: "text"
    ports:
      - 8080:8080
    volumes:
        - ./configs:/configs

