name: Go [lint, test]

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'scripts/**'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '!**.*md'
      - '.github/workflows/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - '*'
    paths:
      - 'scripts/**'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '!**.*md'
      - '.github/workflows/**'

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ 'ubuntu-22.04' ]
        go-version: [1.23.x]
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - run: |
          go version
        shell: bash

      - name: Build
        run: |
          make build
        shell: bash

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: Check release config
        run: |
          make check-releaser
        shell: bash

  testing:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ 'ubuntu-22.04' ]
        go-version: [1.23.x]
    runs-on: ${{ matrix.os }}
    name: Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - run: |
          go version
        shell: bash

      - name: Test
        run: |
          make test
        shell: bash


  check-releaser:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ 'ubuntu-22.04' ]
        go-version: [1.23.x]
    runs-on: ${{ matrix.os }}
    name: Check Releaser
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - run: |
          go version
        shell: bash

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ~> v2
          install-only: true

      - name: Check release config
        run: |
          make check-releaser
        shell: bash


