name: Lint & Test & Build & Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - "!*"

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ 'ubuntu-22.04' ]
        go-version: [1.23.x]
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - run: |
          go version
        shell: bash

      - name: Build
        run: |
          make build

  regression_test:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ 'ubuntu-22.04' ]
        go-version: [1.23.x]
    runs-on: ${{ matrix.os }}
    name: Regression tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - run: |
          go version
        shell: bash

      - name: Run regression tests
        run: |
          make test
        shell: bash

  release:
    needs: [ build, regression_test ]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ 'ubuntu-22.04' ]
        go-version: [1.23.x]
    runs-on: ${{ matrix.os }}
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - run: |
          go version
        shell: bash

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v1.20.0
          install-only: true

      - name: Run GoReleaser
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make release
        shell: bash
